source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PXCoalescedRunner_Example', :exclusive => true do
  pod "PXCoalescedRunner", :path => "../"
end

target 'PXCoalescedRunner_Tests', :exclusive => true do
  pod "PXCoalescedRunner", :path => "../"

  
end
