source 'https://github.com/CocoaPods/Specs.git'

target 'PXCoalescedRunner_Example' do
  pod "PXCoalescedRunner", :path => "../"
end

target 'PXCoalescedRunner_Tests' do
  pod "PXCoalescedRunner", :path => "../"
end
